#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LockScreen.Android.Sample.Resource", IsApplication=true)]

namespace LockScreen.Android.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040004
			public const int activateBtn = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int btnSecondActivity = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int button1 = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int disableBtn = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int enableBtn = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int linearLayout1 = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int rootLayout = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int textView1 = 2130968582;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int SecondLayout = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int app_name = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
